require_relative 'player'
require_relative 'generator'
require_relative 'utils/file_manager'

module Guesser
  POINTS_TO_GO = 3
  NUMBER_LIMIT = 10

  class Game
    include FileManager

    attr_reader :players, :winner

    def initialize(output)
      @output = output
      @winner = nil

      @output.puts '*' * 20
      @output.puts 'Starting the Guesser game!'
      @output.puts "Rules:\nPlayers take turns to guess a number (from 0 to #{NUMBER_LIMIT - 1} generated by computer."
      @output.puts "After players guesses a number, a new one will be generated. The first one to guess #{POINTS_TO_GO}
numbers will become a winner. Have fun!"
      @output.puts '*' * 50

      initialize_players
      play
      show_winner
      print_winner_to_file
    end

    def play
      until @winner do
        @players.each do |player|
          generate_secret_number_for player
          player.waiting_times << measure_time do
            @output.puts "=== It's now #{player.name}'s turn. Enter your guess:"
            if player.guess == player.number_to_guess.secret_number
              @output.puts "You've guessed!"
              player.guessed
            else
              @output.puts("Try again next end turn!")
            end
          end

          if player.won?
            @winner = player
            break
          end
        end

        show_players_statistics
      end
    end

    private

    def initialize_players
      players_count = 0

      until players_count > 0 do
        @output.puts 'How many players?'
        players_count = gets.to_i
      end

      @output.puts "Okay, starting with #{players_count} player(s)..."

      @players = []
      players_count.times do |i|
        @output.puts "Enter a name for player ##{i + 1}"
        @players << Player.new(gets.strip)
      end
    end

    def show_players_statistics
      @players.each { |p| @output.puts p.show_player_statistics }
    end

    def generate_secret_number_for(player)
      sleep 1
      puts "\nPreparing a number to guess..."
      player.number_to_guess ||= Generator.new(NUMBER_LIMIT)
    end

    def show_winner
      @output.puts "\n=== We have a winner! ==="
      @output.puts "#{@winner.name} won the match!"
      @output.puts "Thanks for playing and see you again soon!"
    end

    def print_winner_to_file
      writer = Writer.new('game')
      writer.write("Player #{@winner.name} won at #{Time.now}\n", @winner.show_player_statistics)
    end

    def measure_time
      if block_given?
        time_before = Time.now
        yield
        waited_for = Time.now - time_before
        @output.puts "You were thinking for #{waited_for}s"
        waited_for
      end
    end
  end
end