require_relative 'player'
require_relative 'generator'
require_relative 'utils/file_manager'
require_relative 'utils/args_parser'

module Guesser
  # default values
  POINTS_TO_GO = 3
  NUMBER_LIMIT = 10
  PLAYERS = 2

  class Game
    include FileManager
    include Parser

    attr_reader :players, :winner, :options

    def initialize(output, argv)
      @output, @winner, @options = output, nil, parse_args(argv)
    end

    def start
      welcome
      initialize_players
      play
      show_winner
      print_winner_to_file
    end

    private

    def play
      until @winner do
        @players.each do |player|
          generate_secret_number_for player
          player.waiting_times << measure_time do
            @output.puts "=== It's now #{player.name}'s turn. Enter your guess:"
            if player.guess == player.number_to_guess.secret_number
              @output.puts "You've guessed!"
              player.guessed
            else
              @output.puts("Wrong! Try again next end turn!")
            end
          end

          if player.won?(self)
            @winner = player
            break
          end
        end

        show_players_statistics
      end
    end

    def welcome
      @output.puts '*' * 50
      @output.puts 'Starting the Guesser game!'
      @output.puts "Rules:\nPlayers take turns to guess a number (from 0 to #{NUMBER_LIMIT - 1} generated by computer."
      @output.puts "After player guesses a number, a new one will be generated. The first one to guess #{POINTS_TO_GO} numbers will become a winner. Have fun!"
      @output.puts '*' * 50
    end

    def initialize_players
      @output.puts "Starting the game with #{@options[:players]} player(s)..."

      @players = []
      @options[:players].times do |i|
        @output.puts "Enter a name for player ##{i + 1}"
        @players << Player.new($stdin.gets.strip)
      end
    end

    def show_players_statistics
      @players.each { |p| @output.puts p.show_player_statistics }
    end

    def generate_secret_number_for(player)
      sleep 1
      puts "\nPreparing a number to guess..."
      player.number_to_guess ||= Generator.new(@options[:limit])
    end

    def show_winner
      @output.puts "\n=== We have a winner! ==="
      @output.puts "#{@winner.name} won the match!"
      @output.puts "Thanks for playing and see you again soon!"
    end

    def print_winner_to_file
      writer = Writer.new('game')
      writer.write("Player #{@winner.name} won at #{Time.now}\n", @winner.show_player_statistics)
    end

    def measure_time
      if block_given?
        time_before = Time.now
        yield
        waited_for = Time.now - time_before
        @output.puts "You were thinking for #{waited_for}s"
        waited_for
      end
    end
  end
end